// frontend/src/components/self/Extension.vue
<script setup lang="ts">
import {Command} from "@fzdwx/launcher-api";
import {ChangeExtension, ListInstalled} from "../../../wailsjs/go/main/App";
import {onMounted, ref} from "vue";
import {extensions} from "../../../wailsjs/go/models";
import Extension = extensions.Extension;
import {useViewEvent} from "../../composables/useViewEvent";
import {View} from "../../utils";

const installExtensionList = ref<Extension[]>([]);

onMounted(async () => {
  installExtensionList.value = await ListInstalled();
})

const viewEvent = useViewEvent();
const openExtension = (ext: Extension) => {
  viewEvent.emitter.emit('changeView', View.Extension)
  ChangeExtension(ext)
}
</script>

<template>
  <Command.Group heading="Extension" v-if="installExtensionList">
    <Command.Item v-for="item in installExtensionList"
                  :data-value="item.name"
                  @select="()=>{
                    openExtension(item)
                  }"
    >
      <img :src="item.icon" alt="" style="width: 20px; height: 20px;"/>
      {{ item.name }}
    </Command.Item>
  </Command.Group>
</template>

<style scoped>

</style>

// src/components/items/extension.tsx
import {Command} from "launcher-api";
import {useEffect, useState} from "react";
import {getLocalExtensions, LocalExtension} from "@/native";

const useLocalExtensions = () => {
    const [loading, setLoading] = useState(true)
    const [extensions, setExtensions] = useState<LocalExtension[]>([])

    useEffect(() => {
        setLoading(true)
        getLocalExtensions().then((apps) => {
            setExtensions(apps)
            setLoading(false)
        }).catch((err) => {
            console.log(err)
        })
    }, [])

    return {
        extensions,
        loading
    }
}

const extension = () => {
    const {extensions, loading} = useLocalExtensions()
    return (<Command.Group heading="Extensions">
        {extensions.map((item) => (
            <Command.Item
                key={item.name}
                value={item.name}
                onSelect={() => {
                    window.launcher.openExtension(item)
                }}
            >
                <img className="w-4" alt='img' src={item.icon}/>
                <span>{item.name}</span>
            </Command.Item>
        ))}
        <Command.Item key="Dev Mode" onSelect={() => {
            window.launcher.loadDevView()
        }}>
            <span className="w-4">🛠</span>
            <span>Dev Mode</span>
        </Command.Item>
    </Command.Group>)
}

export default extension
